# To build the image run:
# docker build --file Dockerfile.debian --tag visor-debian .

FROM rust:1.85

WORKDIR /visor

RUN apt-get update && apt-get install -y libgtk-3-dev libasound2-dev

COPY ./crates ./crates
COPY ./examples ./examples
COPY ./visor_cli ./visor_cli
COPY ./visor_core ./visor_core
COPY ./Cargo.toml ./Cargo.toml
COPY ./Cargo.lock ./Cargo.lock
COPY ./rust-toolchain.toml ./rust-toolchain.toml

RUN cargo fetch
RUN cargo build
